import type {Metadata} from 'next'

import './globals.css'

import {sansFont} from '~/components/design-system/fonts'
import {cn} from '~/lib/utils'
import React from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className={cn('min-h-dvh', sansFont.variable)}>
      <body className={'antialiased min-h-dvh bg-beige-100 font-sans'}>{children}</body>
    </html>
  )
}
